/* writing/works.js — GENERATED by writing/build.js. Do not edit by hand.
   Curation lives in writing/build.js (COLLECTIONS); run `node writing/build.js`. */
window.WRITING = {
  "intro": "A back catalogue of creative work in two languages — poetry, short stories, essays, and plays, in Afrikaans and English.",
  "languages": [
    {
      "label": "Afrikaans",
      "slug": "afrikaans",
      "genres": [
        {
          "name": "Poësie",
          "slug": "poetry",
          "collections": [
            {
              "theme": "Die alledaagse",
              "slug": "die-alledaagse",
              "path": "afrikaans/poetry/die-alledaagse",
              "works": [
                {
                  "title": "9:55",
                  "href": "/writing/poetry/9-55/"
                },
                {
                  "title": "Stadswolf",
                  "href": "/writing/poetry/stadswolf/"
                },
                {
                  "title": "Medemens",
                  "href": "/writing/poetry/medemens/"
                },
                {
                  "title": "Nagviooltjie",
                  "href": "/writing/poetry/nagviooltjie/"
                },
                {
                  "title": "Politieke Duif van My",
                  "href": "/writing/poetry/politieke-duif-van-my/"
                },
                {
                  "title": "Kom ons Dans oor Irak",
                  "href": "/writing/poetry/kom-ons-dans-oor-irak/"
                }
              ]
            },
            {
              "theme": "Verlange",
              "slug": "verlange",
              "path": "afrikaans/poetry/verlange",
              "works": [
                {
                  "title": "Iemand",
                  "href": "/writing/poetry/iemand/"
                },
                {
                  "title": "Verlange",
                  "href": "/writing/poetry/verlange/"
                },
                {
                  "title": "Eenrigting-liefde",
                  "href": "/writing/poetry/eenrigting-liefde/"
                },
                {
                  "title": "Weet jy",
                  "href": "/writing/poetry/weet-jy/"
                }
              ]
            },
            {
              "theme": "Liefde",
              "slug": "liefde",
              "path": "afrikaans/poetry/liefde",
              "works": [
                {
                  "title": "Die soen",
                  "href": "/writing/poetry/die-soen/"
                },
                {
                  "title": "Jy",
                  "href": "/writing/poetry/jy/"
                },
                {
                  "title": "Braille",
                  "href": "/writing/poetry/braille/"
                },
                {
                  "title": "Jy’s my berg…",
                  "href": "/writing/poetry/jys-my-berg/"
                },
                {
                  "title": "Geseënd",
                  "href": "/writing/poetry/geseend/"
                },
                {
                  "title": "Lêplek vir 'n kind",
                  "href": "/writing/poetry/leplek-vir-n-kind/"
                },
                {
                  "title": "Die rede",
                  "href": "/writing/poetry/die-rede/"
                },
                {
                  "title": "Liedjie",
                  "href": "/writing/poetry/liedjie/"
                },
                {
                  "title": "Mooi dag",
                  "href": "/writing/poetry/mooi-dag/"
                },
                {
                  "title": "Ballade vir die Reënkind",
                  "href": "/writing/poetry/ballade-vir-die-reenkind/"
                }
              ]
            },
            {
              "theme": "Troue & tuiste",
              "slug": "troue-en-tuiste",
              "path": "afrikaans/poetry/troue-en-tuiste",
              "works": [
                {
                  "title": "Troudag",
                  "href": "/writing/poetry/troudag/"
                },
                {
                  "title": "Hierdie huisie",
                  "href": "/writing/poetry/hierdie-huisie/"
                },
                {
                  "title": "Die wonderwerk",
                  "href": "/writing/poetry/die-wonderwerk/"
                },
                {
                  "title": "Jy is reg",
                  "href": "/writing/poetry/jy-is-reg/"
                }
              ]
            },
            {
              "theme": "By die see",
              "slug": "by-die-see",
              "path": "afrikaans/poetry/by-die-see",
              "works": [
                {
                  "title": "Heroldsbaai",
                  "href": "/writing/poetry/heroldsbaai/"
                },
                {
                  "title": "Spoelgety",
                  "href": "/writing/poetry/spoelgety/"
                },
                {
                  "title": "By die See",
                  "href": "/writing/poetry/by-die-see/"
                },
                {
                  "title": "Rotsgeloop",
                  "href": "/writing/poetry/rotsgeloop/"
                }
              ]
            },
            {
              "theme": "Geloof",
              "slug": "geloof",
              "path": "afrikaans/poetry/geloof",
              "works": [
                {
                  "title": "Alfa",
                  "href": "/writing/poetry/alfa/"
                },
                {
                  "title": "Bekeringslied",
                  "href": "/writing/poetry/bekeringslied/"
                },
                {
                  "title": "Behoud",
                  "href": "/writing/poetry/behoud/"
                },
                {
                  "title": "Pater noster",
                  "href": "/writing/poetry/pater-noster/"
                },
                {
                  "title": "Doodsbegeerte",
                  "href": "/writing/poetry/doodsbegeerte/"
                }
              ]
            },
            {
              "theme": "Verlies & herinnering",
              "slug": "verlies-en-herinnering",
              "path": "afrikaans/poetry/verlies-en-herinnering",
              "works": [
                {
                  "title": "Oupa",
                  "href": "/writing/poetry/oupa/"
                },
                {
                  "title": "Oumsie",
                  "href": "/writing/poetry/oumsie/"
                },
                {
                  "title": "Ou Oom Boesman",
                  "href": "/writing/poetry/ou-oom-boesman/"
                },
                {
                  "title": "Marta?",
                  "href": "/writing/poetry/marta/"
                },
                {
                  "title": "Sewe grepe",
                  "href": "/writing/poetry/sewe-grepe/"
                },
                {
                  "title": "Dode",
                  "href": "/writing/poetry/dode/"
                },
                {
                  "title": "Aan 'n Budjie",
                  "href": "/writing/poetry/aan-n-budjie/"
                },
                {
                  "title": "Ontmoeting en Skeiding",
                  "href": "/writing/poetry/ontmoeting-en-skeiding/"
                },
                {
                  "title": "Icarus Varié",
                  "href": "/writing/poetry/icarus-varie/"
                }
              ]
            },
            {
              "theme": "Self & twyfel",
              "slug": "self-en-twyfel",
              "path": "afrikaans/poetry/self-en-twyfel",
              "works": [
                {
                  "title": "Twyfel",
                  "href": "/writing/poetry/twyfel/"
                },
                {
                  "title": "Genoeg",
                  "href": "/writing/poetry/genoeg/"
                },
                {
                  "title": "Judas van Self",
                  "href": "/writing/poetry/judas-van-self/"
                },
                {
                  "title": "Verstaan My",
                  "href": "/writing/poetry/verstaan-my/"
                },
                {
                  "title": "By die Versilwering van my Donker Wolk",
                  "href": "/writing/poetry/by-die-versilwering-van-my-donker-wolk/"
                }
              ]
            },
            {
              "theme": "Oor musiek & skryf",
              "slug": "oor-musiek-en-skryf",
              "path": "afrikaans/poetry/oor-musiek-en-skryf",
              "works": [
                {
                  "title": "Musiek",
                  "href": "/writing/poetry/musiek/"
                },
                {
                  "title": "Gedagtes oor Musiek en Klank",
                  "href": "/writing/poetry/gedagtes-oor-musiek-en-klank/"
                },
                {
                  "title": "In die Konsertsaal",
                  "href": "/writing/poetry/in-die-konsertsaal/"
                },
                {
                  "title": "Oor my Skryf",
                  "href": "/writing/poetry/oor-my-skryf/"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "label": "English",
      "slug": "english",
      "genres": [
        {
          "name": "Poetry",
          "slug": "poetry",
          "collections": [
            {
              "theme": "Love & longing",
              "slug": "love-en-longing",
              "path": "english/poetry/love-en-longing",
              "works": [
                {
                  "title": "How in Love Am I with Thee?",
                  "href": "/writing/poetry/how-in-love-am-i-with-thee/"
                },
                {
                  "title": "Discovery",
                  "href": "/writing/poetry/discovery/"
                },
                {
                  "title": "Seasons apart",
                  "href": "/writing/poetry/seasons-apart/"
                },
                {
                  "title": "Afar",
                  "href": "/writing/poetry/afar/"
                },
                {
                  "title": "Fighting",
                  "href": "/writing/poetry/fighting/"
                },
                {
                  "title": "You Haunt Me",
                  "href": "/writing/poetry/you-haunt-me/"
                },
                {
                  "title": "Wife to Be",
                  "href": "/writing/poetry/wife-to-be/"
                }
              ]
            },
            {
              "theme": "Devotion & togetherness",
              "slug": "devotion-en-togetherness",
              "path": "english/poetry/devotion-en-togetherness",
              "works": [
                {
                  "title": "God in you",
                  "href": "/writing/poetry/god-in-you/"
                },
                {
                  "title": "Memory",
                  "href": "/writing/poetry/memory/"
                },
                {
                  "title": "I’m here",
                  "href": "/writing/poetry/im-here/"
                }
              ]
            },
            {
              "theme": "Self & shadow",
              "slug": "self-en-shadow",
              "path": "english/poetry/self-en-shadow",
              "works": [
                {
                  "title": "Introspection 1",
                  "href": "/writing/poetry/introspection-1/"
                },
                {
                  "title": "Caught Up in My Dreams",
                  "href": "/writing/poetry/caught-up-in-my-dreams/"
                },
                {
                  "title": "A Mentally Disturbed's Two Meditations on His Behaviour",
                  "href": "/writing/poetry/a-mentally-disturbeds-two-meditations-on-his-behaviour/"
                },
                {
                  "title": "She Is the Product of Each Misjudged Love",
                  "href": "/writing/poetry/she-is-the-product-of-each-misjudged-love/"
                },
                {
                  "title": "Messiah",
                  "href": "/writing/poetry/messiah/"
                }
              ]
            },
            {
              "theme": "Sea, land & journey",
              "slug": "sea-land-en-journey",
              "path": "english/poetry/sea-land-en-journey",
              "works": [
                {
                  "title": "Victoria Falls",
                  "href": "/writing/poetry/victoria-falls/"
                },
                {
                  "title": "On Wandering Around in Africa",
                  "href": "/writing/poetry/on-wandering-around-in-africa/"
                },
                {
                  "title": "Running",
                  "href": "/writing/poetry/running/"
                },
                {
                  "title": "Dead Reckoning",
                  "href": "/writing/poetry/dead-reckoning/"
                },
                {
                  "title": "Under the Tree",
                  "href": "/writing/poetry/under-the-tree/"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};
